services:
  app_proxy:
    environment:
      APP_HOST: kelt-app-store-dcl-market-watch_server_1
      APP_PORT: 8787
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/kumbrel/dcl-market-watch:5.3.0
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      CHECK_INTERVAL: "10"
      DISCORD_WEBHOOK_URL: ""
