services:
  app_proxy:
    environment:
      APP_HOST: dcl-market-watch_server_1
      APP_PORT: 8787
      PROXY_AUTH_ADD: "false"

  server:
    image: python:3.12-slim
    restart: on-failure
    working_dir: /app
    command: sh -c "pip install flask requests && python app.py"
    volumes:
      - ${APP_DATA_DIR}/app:/app
      - ${APP_DATA_DIR}/data:/data
    environment:
      CHECK_INTERVAL: "10"
      DISCORD_WEBHOOK_URL: ""
